# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gix/programming/eclipse/photonfactory

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gix/Dropbox/programming/eclipse/photonfactory

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gix/Dropbox/programming/eclipse/photonfactory/CMakeFiles /home/gix/Dropbox/programming/eclipse/photonfactory/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gix/Dropbox/programming/eclipse/photonfactory/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ray

# Build rule for target.
ray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ray
.PHONY : ray

# fast build rule for target.
ray/fast:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/build
.PHONY : ray/fast

#=============================================================================
# Target rules for targets named ggl

# Build rule for target.
ggl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ggl
.PHONY : ggl

# fast build rule for target.
ggl/fast:
	$(MAKE) -f extern/ggl/CMakeFiles/ggl.dir/build.make extern/ggl/CMakeFiles/ggl.dir/build
.PHONY : ggl/fast

#=============================================================================
# Target rules for targets named oglTest

# Build rule for target.
oglTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oglTest
.PHONY : oglTest

# fast build rule for target.
oglTest/fast:
	$(MAKE) -f extern/ggl/CMakeFiles/oglTest.dir/build.make extern/ggl/CMakeFiles/oglTest.dir/build
.PHONY : oglTest/fast

src/BasicShader.o: src/BasicShader.cc.o
.PHONY : src/BasicShader.o

# target to build an object file
src/BasicShader.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/BasicShader.cc.o
.PHONY : src/BasicShader.cc.o

src/BasicShader.i: src/BasicShader.cc.i
.PHONY : src/BasicShader.i

# target to preprocess a source file
src/BasicShader.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/BasicShader.cc.i
.PHONY : src/BasicShader.cc.i

src/BasicShader.s: src/BasicShader.cc.s
.PHONY : src/BasicShader.s

# target to generate assembly for a file
src/BasicShader.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/BasicShader.cc.s
.PHONY : src/BasicShader.cc.s

src/Camera.o: src/Camera.cc.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Camera.cc.o
.PHONY : src/Camera.cc.o

src/Camera.i: src/Camera.cc.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Camera.cc.i
.PHONY : src/Camera.cc.i

src/Camera.s: src/Camera.cc.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Camera.cc.s
.PHONY : src/Camera.cc.s

src/Color.o: src/Color.cc.o
.PHONY : src/Color.o

# target to build an object file
src/Color.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Color.cc.o
.PHONY : src/Color.cc.o

src/Color.i: src/Color.cc.i
.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Color.cc.i
.PHONY : src/Color.cc.i

src/Color.s: src/Color.cc.s
.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Color.cc.s
.PHONY : src/Color.cc.s

src/Matrix4x4.o: src/Matrix4x4.cc.o
.PHONY : src/Matrix4x4.o

# target to build an object file
src/Matrix4x4.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Matrix4x4.cc.o
.PHONY : src/Matrix4x4.cc.o

src/Matrix4x4.i: src/Matrix4x4.cc.i
.PHONY : src/Matrix4x4.i

# target to preprocess a source file
src/Matrix4x4.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Matrix4x4.cc.i
.PHONY : src/Matrix4x4.cc.i

src/Matrix4x4.s: src/Matrix4x4.cc.s
.PHONY : src/Matrix4x4.s

# target to generate assembly for a file
src/Matrix4x4.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Matrix4x4.cc.s
.PHONY : src/Matrix4x4.cc.s

src/Plane.o: src/Plane.cc.o
.PHONY : src/Plane.o

# target to build an object file
src/Plane.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Plane.cc.o
.PHONY : src/Plane.cc.o

src/Plane.i: src/Plane.cc.i
.PHONY : src/Plane.i

# target to preprocess a source file
src/Plane.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Plane.cc.i
.PHONY : src/Plane.cc.i

src/Plane.s: src/Plane.cc.s
.PHONY : src/Plane.s

# target to generate assembly for a file
src/Plane.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Plane.cc.s
.PHONY : src/Plane.cc.s

src/Pngexp.o: src/Pngexp.cc.o
.PHONY : src/Pngexp.o

# target to build an object file
src/Pngexp.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Pngexp.cc.o
.PHONY : src/Pngexp.cc.o

src/Pngexp.i: src/Pngexp.cc.i
.PHONY : src/Pngexp.i

# target to preprocess a source file
src/Pngexp.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Pngexp.cc.i
.PHONY : src/Pngexp.cc.i

src/Pngexp.s: src/Pngexp.cc.s
.PHONY : src/Pngexp.s

# target to generate assembly for a file
src/Pngexp.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Pngexp.cc.s
.PHONY : src/Pngexp.cc.s

src/Raytracer.o: src/Raytracer.cc.o
.PHONY : src/Raytracer.o

# target to build an object file
src/Raytracer.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Raytracer.cc.o
.PHONY : src/Raytracer.cc.o

src/Raytracer.i: src/Raytracer.cc.i
.PHONY : src/Raytracer.i

# target to preprocess a source file
src/Raytracer.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Raytracer.cc.i
.PHONY : src/Raytracer.cc.i

src/Raytracer.s: src/Raytracer.cc.s
.PHONY : src/Raytracer.s

# target to generate assembly for a file
src/Raytracer.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Raytracer.cc.s
.PHONY : src/Raytracer.cc.s

src/Scene.o: src/Scene.cc.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Scene.cc.o
.PHONY : src/Scene.cc.o

src/Scene.i: src/Scene.cc.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Scene.cc.i
.PHONY : src/Scene.cc.i

src/Scene.s: src/Scene.cc.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Scene.cc.s
.PHONY : src/Scene.cc.s

src/Screen.o: src/Screen.cc.o
.PHONY : src/Screen.o

# target to build an object file
src/Screen.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Screen.cc.o
.PHONY : src/Screen.cc.o

src/Screen.i: src/Screen.cc.i
.PHONY : src/Screen.i

# target to preprocess a source file
src/Screen.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Screen.cc.i
.PHONY : src/Screen.cc.i

src/Screen.s: src/Screen.cc.s
.PHONY : src/Screen.s

# target to generate assembly for a file
src/Screen.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Screen.cc.s
.PHONY : src/Screen.cc.s

src/Sphere.o: src/Sphere.cc.o
.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Sphere.cc.o
.PHONY : src/Sphere.cc.o

src/Sphere.i: src/Sphere.cc.i
.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Sphere.cc.i
.PHONY : src/Sphere.cc.i

src/Sphere.s: src/Sphere.cc.s
.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Sphere.cc.s
.PHONY : src/Sphere.cc.s

src/SurfacePoint.o: src/SurfacePoint.cc.o
.PHONY : src/SurfacePoint.o

# target to build an object file
src/SurfacePoint.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/SurfacePoint.cc.o
.PHONY : src/SurfacePoint.cc.o

src/SurfacePoint.i: src/SurfacePoint.cc.i
.PHONY : src/SurfacePoint.i

# target to preprocess a source file
src/SurfacePoint.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/SurfacePoint.cc.i
.PHONY : src/SurfacePoint.cc.i

src/SurfacePoint.s: src/SurfacePoint.cc.s
.PHONY : src/SurfacePoint.s

# target to generate assembly for a file
src/SurfacePoint.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/SurfacePoint.cc.s
.PHONY : src/SurfacePoint.cc.s

src/Triangle.o: src/Triangle.cc.o
.PHONY : src/Triangle.o

# target to build an object file
src/Triangle.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Triangle.cc.o
.PHONY : src/Triangle.cc.o

src/Triangle.i: src/Triangle.cc.i
.PHONY : src/Triangle.i

# target to preprocess a source file
src/Triangle.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Triangle.cc.i
.PHONY : src/Triangle.cc.i

src/Triangle.s: src/Triangle.cc.s
.PHONY : src/Triangle.s

# target to generate assembly for a file
src/Triangle.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Triangle.cc.s
.PHONY : src/Triangle.cc.s

src/Triangle2d.o: src/Triangle2d.cc.o
.PHONY : src/Triangle2d.o

# target to build an object file
src/Triangle2d.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Triangle2d.cc.o
.PHONY : src/Triangle2d.cc.o

src/Triangle2d.i: src/Triangle2d.cc.i
.PHONY : src/Triangle2d.i

# target to preprocess a source file
src/Triangle2d.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Triangle2d.cc.i
.PHONY : src/Triangle2d.cc.i

src/Triangle2d.s: src/Triangle2d.cc.s
.PHONY : src/Triangle2d.s

# target to generate assembly for a file
src/Triangle2d.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/Triangle2d.cc.s
.PHONY : src/Triangle2d.cc.s

src/YafImport.o: src/YafImport.cc.o
.PHONY : src/YafImport.o

# target to build an object file
src/YafImport.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/YafImport.cc.o
.PHONY : src/YafImport.cc.o

src/YafImport.i: src/YafImport.cc.i
.PHONY : src/YafImport.i

# target to preprocess a source file
src/YafImport.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/YafImport.cc.i
.PHONY : src/YafImport.cc.i

src/YafImport.s: src/YafImport.cc.s
.PHONY : src/YafImport.s

# target to generate assembly for a file
src/YafImport.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/YafImport.cc.s
.PHONY : src/YafImport.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/main.cc.s
.PHONY : src/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ray"
	@echo "... rebuild_cache"
	@echo "... ggl"
	@echo "... oglTest"
	@echo "... src/BasicShader.o"
	@echo "... src/BasicShader.i"
	@echo "... src/BasicShader.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/Matrix4x4.o"
	@echo "... src/Matrix4x4.i"
	@echo "... src/Matrix4x4.s"
	@echo "... src/Plane.o"
	@echo "... src/Plane.i"
	@echo "... src/Plane.s"
	@echo "... src/Pngexp.o"
	@echo "... src/Pngexp.i"
	@echo "... src/Pngexp.s"
	@echo "... src/Raytracer.o"
	@echo "... src/Raytracer.i"
	@echo "... src/Raytracer.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Screen.o"
	@echo "... src/Screen.i"
	@echo "... src/Screen.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/SurfacePoint.o"
	@echo "... src/SurfacePoint.i"
	@echo "... src/SurfacePoint.s"
	@echo "... src/Triangle.o"
	@echo "... src/Triangle.i"
	@echo "... src/Triangle.s"
	@echo "... src/Triangle2d.o"
	@echo "... src/Triangle2d.i"
	@echo "... src/Triangle2d.s"
	@echo "... src/YafImport.o"
	@echo "... src/YafImport.i"
	@echo "... src/YafImport.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

